In [2]:
#Claire Roush
#claireroush@gmail.com
#1/2/17
#The original CSV was data scraped from http://db.desmoinesregister.com with the ParseHub Project
#2013 City of Des Moines Parks and Recreation employee data
#The original CSV had serious formatting errors. This notebook's project is to clean and organize the data, and write to CSV.
#The only relevant (saved) attributes include Name, Title, Yearly Wage, Hourly Rate, Years Employed

import pandas
df = pandas.read_csv("run_results.csv")
cols = ["Name", "Title", "Wage", "Rate", "Years"]
new_df = pandas.DataFrame(columns = cols)

print(df.shape[0])
i=1 #skip the first useless row
j=0 #index into the new df
while i < df.shape[0]-1:
    new_df.loc[j] = [df.loc[i][0], df.loc[i+1][1], df.loc[i+3][1], df.loc[i+4][1], df.loc[i+5][1]]
    print(new_df.loc[j])
    i=i+7
    j=j+1

new_df.to_csv("cleaned_data.csv")

896
Name           BENJAMIN PAGE
Title    Park & Rec Director
Wage            $119,766.40
Rate                 $57.60
Years                    5.8
Name: 0, dtype: object
Name           KEVIN C MORAN
Title    Senior Park Planner
Wage             $87,469.20
Rate                 $42.10
Years                   12.5
Name: 1, dtype: object
Name     RONALD S WARD
Title    Parks Manager
Wage       $87,276.80
Rate           $42.00
Years              1.1
Name: 2, dtype: object
Name        MATTHEW A SALVATORE
Title    Administrative Analyst
Wage                $83,835.80
Rate                    $40.30
Years                       0.9
Name: 3, dtype: object
Name                BRIAN H BECKER
Title    Park & Rec Superintendent
Wage                   $83,304.00
Rate                       $40.10
Years                         16.3
Name: 4, dtype: object
Name                JOHN A HAGENER
Title    Park & Rec Superintendent
Wage                   $83,304.00
Rate                       $40.10
Years                         15.9
Name: 5, dtype: object
Name                  RICHARD E LEFLEUR
Title    Buildings & Grounds Superintnd
Wage                        $83,304.00
Rate                            $40.10
Years                                21
Name: 6, dtype: object
Name     MARLENE ANDERSON-BEATTIE
Title       Park & Rec Supervisor
Wage                  $77,706.70
Rate                      $37.40
Years                        18.8
Name: 7, dtype: object
Name                   KIRK J ROBINSON
Title    Bldg & Parks Maint Supervisor
Wage                       $77,875.20
Rate                           $37.40
Years                              5.7
Name: 8, dtype: object
Name        JENNIFER FLETCHER
Title    Marketing Supervisor
Wage              $74,006.40
Rate                  $35.60
Years                     2.3
Name: 9, dtype: object
Name               MICHAEL GAUL
Title    Horticulture Inspector
Wage                $74,006.40
Rate                    $35.60
Years                      11.4
Name: 10, dtype: object
Name             JULIE M HEMPEL
Title    Horticulture Inspector
Wage                $74,006.40
Rate                    $35.60
Years                       7.8
Name: 11, dtype: object
Name            ROBIN R LEAPER
Title    Park & Rec Supervisor
Wage               $74,006.40
Rate                   $35.60
Years                     13.4
Name: 12, dtype: object
Name      RICHARD R BROWN
Title    Park Planner III
Wage          $71,884.80
Rate              $34.60
Years                  12
Name: 13, dtype: object
Name     LEONARD B BALLARD
Title          Electrician
Wage           $68,640.00
Rate               $33.00
Years                   22
Name: 14, dtype: object
Name     RANDY R HOWARD
Title       Electrician
Wage        $68,640.00
Rate            $33.00
Years              22.8
Name: 15, dtype: object
Name                ALLEN W WAGNER
Title    Air-Conditioning Mechanic
Wage                   $68,640.00
Rate                       $33.00
Years                         20.6
Name: 16, dtype: object
Name                 DEANNA LYN CLAUSEN
Title    Cemetary Operations Supervisor
Wage                        $66,726.40
Rate                            $32.10
Years                              31.6
Name: 17, dtype: object
Name     CALLIE H LE'AU COURTRIGHT
Title        Park & Rec Supervisor
Wage                   $65,748.80
Rate                       $31.60
Years                            5
Name: 18, dtype: object
Name     LARRY FRE EDRIS
Title    Park Planner II
Wage         $65,416.00
Rate             $31.50
Years               16.8
Name: 19, dtype: object
Name       MINDY S MOORE
Title    Park Planner II
Wage         $65,416.00
Rate             $31.50
Years                6.1
Name: 20, dtype: object
Name                 KENNETH WAY BALL
Title    Park Construction Technician
Wage                      $63,939.20
Rate                          $30.70
Years                            34.5
Name: 21, dtype: object
Name                   KEVIN D HALL
Title    Climate Control Technician
Wage                    $63,939.20
Rate                        $30.70
Years                          20.2
Name: 22, dtype: object
Name                RANDALL B PECK
Title    Medium Equipment Operator
Wage                   $63,939.20
Rate                       $30.70
Years                         23.1
Name: 23, dtype: object
Name                    JAMES O PIPER
Title    Park Construction Technician
Wage                      $63,939.20
Rate                          $30.70
Years                            11.7
Name: 24, dtype: object
Name     CHRISTOPHER M MILLER
Title             Electrician
Wage              $62,462.40
Rate                  $30.00
Years                     0.6
Name: 25, dtype: object
Name           TIMOTHY A SMITH
Title    Park & Rec Supervisor
Wage               $61,963.20
Rate                   $29.80
Years                       17
Name: 26, dtype: object
Name                 JIMMIE L BENNETT
Title    Senior Maintenance Carpenter
Wage                      $61,027.20
Rate                          $29.30
Years                             5.1
Name: 27, dtype: object
Name                 MARTIN F. DOBSON
Title    Senior Maintenance Carpenter
Wage                      $61,027.20
Rate                          $29.30
Years                            13.8
Name: 28, dtype: object
Name     RUSSELL T ENGLISH
Title              Plumber
Wage           $61,027.20
Rate               $29.30
Years                  2.3
Name: 29, dtype: object
Name     MICHAEL T GIBBS
Title            Plumber
Wage         $61,027.20
Rate             $29.30
Years                  9
Name: 30, dtype: object
Name                  DANIEL A HEJKAL
Title    Senior Maintenance Carpenter
Wage                      $61,027.20
Rate                          $29.30
Years                             2.3
Name: 31, dtype: object
Name               KEVIN D HOLZHAUSER
Title    Senior Maintenance Carpenter
Wage                      $61,027.20
Rate                          $29.30
Years                             2.3
Name: 32, dtype: object
Name                    JAMES P HYLER
Title    Senior Maintenance Carpenter
Wage                      $61,027.20
Rate                          $29.30
Years                            12.6
Name: 33, dtype: object
Name       HOA V LUU
Title        Painter
Wage     $61,027.20
Rate         $29.30
Years           15.7
Name: 34, dtype: object
Name                    DANNY OLANDER
Title    Senior Maintenance Carpenter
Wage                      $61,027.20
Rate                          $29.30
Years                            13.6
Name: 35, dtype: object
Name                SANTINO R VALADEZ
Title    Senior Maintenance Carpenter
Wage                      $61,027.20
Rate                          $29.30
Years                             2.3
Name: 36, dtype: object
Name     RONALD J MACHIR
Title            Painter
Wage         $59,779.20
Rate             $28.70
Years                0.6
Name: 37, dtype: object
Name              RANDAL D BURNETT
Title    Medium Equipment Operator
Wage                   $59,009.60
Rate                       $28.40
Years                         33.3
Name: 38, dtype: object
Name           ANTHONY J RUSSO
Title    Irrigation Technician
Wage               $59,009.60
Rate                   $28.40
Years                     13.4
Name: 39, dtype: object
Name                    MICHAEL J SLOAN
Title    Sr Building Equipment Operator
Wage                        $59,009.60
Rate                            $28.40
Years                              15.8
Name: 40, dtype: object
Name                  DENNIS E SMITH
Title    Cemetery Equipment Operator
Wage                     $59,009.60
Rate                         $28.40
Years                           24.5
Name: 41, dtype: object
Name                   KEVIN L THOMPSON
Title    Sr Building Equipment Operator
Wage                        $59,009.60
Rate                            $28.40
Years                              12.1
Name: 42, dtype: object
Name            CARYL D VANDERKAMP
Title    Medium Equipment Operator
Wage                   $59,009.60
Rate                       $28.40
Years                         14.5
Name: 43, dtype: object
Name                  JOHN C WOOLSON
Title    Cemetery Equipment Operator
Wage                     $59,009.60
Rate                         $28.40
Years                           21.4
Name: 44, dtype: object
Name     JAMES M THOMPSON
Title             Painter
Wage          $58,489.60
Rate              $28.10
Years                 0.4
Name: 45, dtype: object
Name          JOEL M VANROEKEL
Title    Park & Rec Supervisor
Wage               $58,406.40
Rate                   $28.10
Years                      0.2
Name: 46, dtype: object
Name     LEE A WHEELOCK
Title      Park Planner
Wage        $57,096.00
Rate            $27.50
Years               3.9
Name: 47, dtype: object
Name               RONALD W BURT
Title    Park Maintenance Worker
Wage                 $56,587.40
Rate                     $27.20
Years                       24.2
Name: 48, dtype: object
Name               PAUL V STROME
Title    Park Maintenance Worker
Wage                 $56,587.40
Rate                     $27.20
Years                       12.4
Name: 49, dtype: object
Name                    MICHAEL D MOORE
Title    Sr Building Equipment Operator
Wage                        $56,451.20
Rate                            $27.10
Years                                 5
Name: 50, dtype: object
Name                   BARBARA L BAKER
Title    Recreation Program Supervisor
Wage                       $55,057.60
Rate                           $26.50
Years                              6.5
Name: 51, dtype: object
Name                 REBECCA J LINHART
Title    Executive Administrative Asst
Wage                       $55,057.60
Rate                           $26.50
Years                               13
Name: 52, dtype: object
Name             DENNIS L DEGNER
Title    Park Maintenance Worker
Wage                 $53,892.80
Rate                     $25.90
Years                        6.4
Name: 53, dtype: object
Name             RICKEY R FISCEL
Title    Park Maintenance Worker
Wage                 $53,892.80
Rate                     $25.90
Years                       22.8
Name: 54, dtype: object
Name            KATHLEEN A HIATT
Title    Park Maintenance Worker
Wage                 $53,892.80
Rate                     $25.90
Years                         25
Name: 55, dtype: object
Name             JASON J JOHNSON
Title    Park Maintenance Worker
Wage                 $53,892.80
Rate                     $25.90
Years                       13.5
Name: 56, dtype: object
Name           KENT K KEHLENBECK
Title    Park Maintenance Worker
Wage                 $53,892.80
Rate                     $25.90
Years                       16.6
Name: 57, dtype: object
Name          PATRICK M SLYKHUIS
Title    Park Maintenance Worker
Wage                 $53,892.80
Rate                     $25.90
Years                       14.7
Name: 58, dtype: object
Name            KENNETH R TRYTEK
Title    Park Maintenance Worker
Wage                 $53,892.80
Rate                     $25.90
Years                       16.3
Name: 59, dtype: object
Name           SHARON K NEFF
Title    Administrative Aide
Wage             $52,811.20
Rate                 $25.40
Years                     24
Name: 60, dtype: object
Name               BRYAN P DAVIS
Title    Park Maintenance Worker
Wage                 $51,500.80
Rate                     $24.80
Years                        8.6
Name: 61, dtype: object
Name        DENNIS D STREYFFELER
Title    Park Maintenance Worker
Wage                 $51,500.80
Rate                     $24.80
Years                       14.7
Name: 62, dtype: object
Name            THOMAS F BENNETT
Title    Parks Technician - 7 mo
Wage                 $49,296.00
Rate                     $23.70
Years                        0.4
Name: 63, dtype: object
Name             KYLE D COURTNEY
Title    Horticulture Technician
Wage                 $49,296.00
Rate                     $23.70
Years                       17.1
Name: 64, dtype: object
Name                GARY A CROSS
Title    Horticulture Technician
Wage                 $49,296.00
Rate                     $23.70
Years                       23.5
Name: 65, dtype: object
Name             JEFFREY J DODGE
Title    Horticulture Technician
Wage                 $24,648.00
Rate                     $23.70
Years                          4
Name: 66, dtype: object
Name     TERRY M DOTTS
Title     Truck Driver
Wage       $49,296.00
Rate           $23.70
Years             16.7
Name: 67, dtype: object
Name           SHANNON A MORRILL
Title    Horticulture Technician
Wage                 $24,648.00
Rate                     $23.70
Years                        7.4
Name: 68, dtype: object
Name                     JEAN M MURRAY
Title    Conservatory/Grnhse Hort Tech
Wage                       $49,296.00
Rate                           $23.70
Years                              7.5
Name: 69, dtype: object
Name                 DOUG NELSEN
Title    Parks Technician - 7 mo
Wage                 $49,296.00
Rate                     $23.70
Years                        0.4
Name: 70, dtype: object
Name              JIM L SPURLING
Title    Parks Technician - 7 mo
Wage                 $49,296.00
Rate                     $23.70
Years                        0.4
Name: 71, dtype: object
Name     MARTY D SUTHERLAND
Title          Truck Driver
Wage            $49,296.00
Rate                $23.70
Years                  18.5
Name: 72, dtype: object
Name                    SARAH J WARNER
Title    Conservatory/Grnhse Hort Tech
Wage                       $24,648.00
Rate                           $23.70
Years                              5.3
Name: 73, dtype: object
Name     CHARLES L HASTINGS
Title               Laborer
Wage            $48,505.60
Rate                $23.30
Years                  16.5
Name: 74, dtype: object
Name     GARY W REDBURN
Title           Laborer
Wage        $48,505.60
Rate            $23.30
Years              25.2
Name: 75, dtype: object
Name               HOLLY M BRAZELTON
Title    Senior Customer Service Rep
Wage                     $47,153.60
Rate                         $22.70
Years                           11.6
Name: 76, dtype: object
Name              JOSHUA N DEWES
Title    Park Maintenance Worker
Wage                 $45,094.40
Rate                     $21.70
Years                        0.3
Name: 77, dtype: object
Name              JASON W FISCEL
Title    Park Maintenance Worker
Wage                 $45,094.40
Rate                     $21.70
Years                        0.4
Name: 78, dtype: object
Name             JAMES D PLUMMER
Title    Park Maintenance Worker
Wage                 $45,094.40
Rate                     $21.70
Years                        0.4
Name: 79, dtype: object
Name              MICHAEL S TODD
Title    Park Maintenance Worker
Wage                 $45,094.40
Rate                     $21.70
Years                        0.4
Name: 80, dtype: object
Name                  MICHELLE A KINNEY
Title    Recreation Program Coordinator
Wage                        $20,036.60
Rate                            $20.30
Years                               3.6
Name: 81, dtype: object
Name                     FRANK G MARTIN
Title    Seasonal Construction Inspectr
Wage                        $42,182.40
Rate                            $20.30
Years                               0.4
Name: 82, dtype: object
Name               RALAINE M MASSEY
Title    Parks Customer Service Rep
Wage                    $42,182.40
Rate                        $20.30
Years                          18.8
Name: 83, dtype: object
Name              JULIE D. WIEZOREK
Title    Parks Customer Service Rep
Wage                    $42,182.40
Rate                        $20.30
Years                          13.3
Name: 84, dtype: object
Name                  STEPHEN A KITCHEN
Title    Recreation Program Coordinator
Wage                        $41,558.40
Rate                            $20.00
Years                               0.2
Name: 85, dtype: object
Name              KARI J AALBERS
Title    Parks Technician - 7 mo
Wage                 $41,412.80
Rate                     $19.90
Years                        0.4
Name: 86, dtype: object
Name             DAVE L ANDERSON
Title    Parks Technician - 7 mo
Wage                 $41,412.80
Rate                     $19.90
Years                        0.4
Name: 87, dtype: object
Name              MIA COUNTRYMAN
Title    Parks Technician - 7 mo
Wage                 $41,412.80
Rate                     $19.90
Years                        0.3
Name: 88, dtype: object
Name             JESSICA FORTNEY
Title    Parks Technician - 7 mo
Wage                 $41,412.80
Rate                     $19.90
Years                        0.4
Name: 89, dtype: object
Name             SUSAN M HARTNEY
Title    Parks Technician - 7 mo
Wage                 $41,412.80
Rate                     $19.90
Years                        0.4
Name: 90, dtype: object
Name            LERON L JENNINGS
Title    Parks Technician - 7 mo
Wage                 $41,412.80
Rate                     $19.90
Years                        0.4
Name: 91, dtype: object
Name              MARK J JOHNSON
Title    Parks Technician - 7 mo
Wage                 $41,412.80
Rate                     $19.90
Years                        0.4
Name: 92, dtype: object
Name               DANIEL R JUST
Title    Parks Technician - 7 mo
Wage                 $41,412.80
Rate                     $19.90
Years                        0.4
Name: 93, dtype: object
Name            THOMAS P LANSING
Title    Parks Technician - 7 mo
Wage                 $41,412.80
Rate                     $19.90
Years                        0.6
Name: 94, dtype: object
Name                RYAN W MEYER
Title    Parks Technician - 7 mo
Wage                 $41,412.80
Rate                     $19.90
Years                        0.4
Name: 95, dtype: object
Name            KANE L MICHELSEN
Title    Parks Technician - 7 mo
Wage                 $41,412.80
Rate                     $19.90
Years                        0.3
Name: 96, dtype: object
Name            KYLE H MICHELSEN
Title    Parks Technician - 7 mo
Wage                 $41,412.80
Rate                     $19.90
Years                        0.3
Name: 97, dtype: object
Name               JOHN MILLISON
Title    Parks Technician - 7 mo
Wage                 $41,412.80
Rate                     $19.90
Years                        0.3
Name: 98, dtype: object
Name              RANDY J POWELL
Title    Parks Technician - 7 mo
Wage                 $41,412.80
Rate                     $19.90
Years                        0.4
Name: 99, dtype: object
Name             PARKER A WATSON
Title    Parks Technician - 7 mo
Wage                 $41,412.80
Rate                     $19.90
Years                        0.4
Name: 100, dtype: object
Name                  JANICE K PARK
Title    Parks Customer Service Rep
Wage                    $38,750.40
Rate                        $18.60
Years                          12.6
Name: 101, dtype: object
Name                    NICOLE D MCLUEN
Title    Recreation Program Coordinator
Wage                        $37,211.20
Rate                            $17.90
Years                               1.4
Name: 102, dtype: object
Name                  KATHY SUE MYERS
Title    Cemetery Client Services Rep
Wage                       $7,442.20
Rate                          $17.90
Years                            25.2
Name: 103, dtype: object
Name                    JOHN C TERPKOSH
Title    Recreation Program Coordinator
Wage                        $18,605.60
Rate                            $17.90
Years                              17.7
Name: 104, dtype: object
Name                        JILL C BURT
Title    Recreation Program Coordinator
Wage                        $17,815.20
Rate                            $17.10
Years                               0.6